server:
    port: 8080

spring:
    application:
        name: costumer
    datasource:
        username: 'username'
        url: jdbc:postgres://localhost:5432/costumer
        password: password
        jpa:
            properties:
                    hibernate:
                        dialect: org.hibernate.dialect.PostgreSQLDialect
                        format_sql: true
            hibernate:
                ddl-auto: update
            show-sql: true
